import {
  MemberProfile,
  MemberSession,
  MemberConversation,
  MemberMessage,
  MemberStats,
  DisciplineBreakdown,
  Milestone,
  JournalEntry,
  ActivityDay,
  ActivityItem,
  PaymentMethod,
  BillingRecord,
  NotificationPrefs,
} from "./types";

// ── Profile ──
export const memberProfile: MemberProfile = {
  id: "m-1",
  firstName: "Sarah",
  lastName: "Chen",
  email: "sarah.chen@email.com",
  phone: "+1 555-0102",
  timezone: "America/New_York",
  language: "English",
  avatarInitials: "SC",
  memberSince: "2025-10-03",
  preferredDisciplines: ["Breathwork", "Yoga"],
  preferredSessionLength: 60,
};

// ── Stats ──
export const memberStats: MemberStats = {
  totalSessions: 18,
  currentStreak: 4,
  totalHours: 16,
  nextSessionIn: "2 days",
};

// ── Sessions ──
export const memberSessions: MemberSession[] = [
  // Upcoming
  {
    id: "s-1",
    teacherName: "Maya Reyes",
    teacherInitials: "MR",
    teacherSlug: "maya-reyes",
    discipline: "Breathwork",
    date: "2026-04-11",
    time: "10:00 AM",
    duration: 60,
    status: "confirmed",
    price: 65,
    reviewed: false,
  },
  {
    id: "s-2",
    teacherName: "Carlos Vega",
    teacherInitials: "CV",
    teacherSlug: "carlos-vega",
    discipline: "Yoga",
    date: "2026-04-14",
    time: "2:00 PM",
    duration: 60,
    status: "confirmed",
    price: 70,
    reviewed: false,
  },
  {
    id: "s-3",
    teacherName: "Lena Park",
    teacherInitials: "LP",
    teacherSlug: "lena-park",
    discipline: "Meditation",
    date: "2026-04-18",
    time: "9:00 AM",
    duration: 45,
    status: "confirmed",
    price: 80,
    reviewed: false,
  },
  // Past
  {
    id: "s-4",
    teacherName: "Maya Reyes",
    teacherInitials: "MR",
    teacherSlug: "maya-reyes",
    discipline: "Breathwork",
    date: "2026-04-07",
    time: "10:00 AM",
    duration: 60,
    status: "completed",
    price: 65,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-5",
    teacherName: "Carlos Vega",
    teacherInitials: "CV",
    teacherSlug: "carlos-vega",
    discipline: "Yoga",
    date: "2026-04-03",
    time: "2:00 PM",
    duration: 60,
    status: "completed",
    price: 70,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-6",
    teacherName: "Anika Sharma",
    teacherInitials: "AS",
    teacherSlug: "anika-sharma",
    discipline: "Somatic",
    date: "2026-03-28",
    time: "11:00 AM",
    duration: 60,
    status: "completed",
    price: 85,
    reviewed: false,
  },
  {
    id: "s-7",
    teacherName: "Maya Reyes",
    teacherInitials: "MR",
    teacherSlug: "maya-reyes",
    discipline: "Meditation",
    date: "2026-03-24",
    time: "10:00 AM",
    duration: 60,
    status: "completed",
    price: 65,
    rating: 4,
    reviewed: true,
  },
  {
    id: "s-8",
    teacherName: "James Okafor",
    teacherInitials: "JO",
    teacherSlug: "james-okafor",
    discipline: "Yoga",
    date: "2026-03-20",
    time: "3:00 PM",
    duration: 60,
    status: "completed",
    price: 75,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-9",
    teacherName: "Lena Park",
    teacherInitials: "LP",
    teacherSlug: "lena-park",
    discipline: "Meditation",
    date: "2026-03-17",
    time: "9:00 AM",
    duration: 45,
    status: "completed",
    price: 80,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-10",
    teacherName: "Carlos Vega",
    teacherInitials: "CV",
    teacherSlug: "carlos-vega",
    discipline: "Yoga",
    date: "2026-03-12",
    time: "2:00 PM",
    duration: 60,
    status: "completed",
    price: 70,
    reviewed: false,
  },
  {
    id: "s-11",
    teacherName: "Maya Reyes",
    teacherInitials: "MR",
    teacherSlug: "maya-reyes",
    discipline: "Breathwork",
    date: "2026-03-07",
    time: "10:00 AM",
    duration: 60,
    status: "completed",
    price: 65,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-12",
    teacherName: "Kwame Mensah",
    teacherInitials: "KM",
    teacherSlug: "kwame-mensah",
    discipline: "Meditation",
    date: "2026-03-03",
    time: "11:00 AM",
    duration: 60,
    status: "completed",
    price: 70,
    rating: 4,
    reviewed: true,
  },
  {
    id: "s-13",
    teacherName: "Priya Nair",
    teacherInitials: "PN",
    teacherSlug: "priya-nair",
    discipline: "Somatic",
    date: "2026-02-27",
    time: "4:00 PM",
    duration: 60,
    status: "completed",
    price: 90,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-14",
    teacherName: "Maya Reyes",
    teacherInitials: "MR",
    teacherSlug: "maya-reyes",
    discipline: "Breathwork",
    date: "2026-02-21",
    time: "10:00 AM",
    duration: 60,
    status: "completed",
    price: 65,
    rating: 5,
    reviewed: true,
  },
  {
    id: "s-15",
    teacherName: "James Okafor",
    teacherInitials: "JO",
    teacherSlug: "james-okafor",
    discipline: "Yoga",
    date: "2026-02-14",
    time: "3:00 PM",
    duration: 60,
    status: "completed",
    price: 75,
    rating: 4,
    reviewed: true,
  },
  // Cancelled
  {
    id: "s-16",
    teacherName: "Nora Eriksen",
    teacherInitials: "NE",
    teacherSlug: "nora-eriksen",
    discipline: "Yoga",
    date: "2026-03-31",
    time: "1:00 PM",
    duration: 60,
    status: "cancelled",
    price: 75,
    reviewed: false,
    cancelledBy: "teacher",
    cancellationReason: "Teacher unavailable due to illness",
  },
  {
    id: "s-17",
    teacherName: "David Cohen",
    teacherInitials: "DC",
    teacherSlug: "david-cohen",
    discipline: "Meditation",
    date: "2026-03-15",
    time: "10:00 AM",
    duration: 60,
    status: "cancelled",
    price: 85,
    reviewed: false,
    cancelledBy: "member",
    cancellationReason: "Schedule conflict",
  },
];

// ── Conversations ──
export const memberConversations: MemberConversation[] = [
  {
    id: "c-1",
    teacherName: "Maya Reyes",
    teacherInitials: "MR",
    teacherSlug: "maya-reyes",
    lastMessage: "Looking forward to our session on Friday!",
    lastMessageTime: "10:32 AM",
    unread: 1,
    online: true,
  },
  {
    id: "c-2",
    teacherName: "Carlos Vega",
    teacherInitials: "CV",
    teacherSlug: "carlos-vega",
    lastMessage: "Great progress this week. Remember to practice the hip openers.",
    lastMessageTime: "Yesterday",
    unread: 0,
    online: false,
  },
  {
    id: "c-3",
    teacherName: "Lena Park",
    teacherInitials: "LP",
    teacherSlug: "lena-park",
    lastMessage: "I've sent you some guided meditation tracks to try before our next session.",
    lastMessageTime: "Apr 6",
    unread: 2,
    online: true,
  },
  {
    id: "c-4",
    teacherName: "James Okafor",
    teacherInitials: "JO",
    teacherSlug: "james-okafor",
    lastMessage: "Thanks for the review! Really appreciate it.",
    lastMessageTime: "Mar 21",
    unread: 0,
    online: false,
  },
  {
    id: "c-5",
    teacherName: "Anika Sharma",
    teacherInitials: "AS",
    teacherSlug: "anika-sharma",
    lastMessage: "How are you feeling after the somatic session?",
    lastMessageTime: "Mar 29",
    unread: 1,
    online: false,
  },
];

export const memberMessages: Record<string, MemberMessage[]> = {
  "c-1": [
    { id: "m-1-1", conversationId: "c-1", sender: "system", text: "Session scheduled: Breathwork on Apr 11 at 10:00 AM", timestamp: "Apr 8, 9:00 AM", read: true },
    { id: "m-1-2", conversationId: "c-1", sender: "member", text: "Hi Maya! Just booked our next session. I've been practicing the breathing pattern you taught me.", timestamp: "Apr 8, 9:15 AM", read: true },
    { id: "m-1-3", conversationId: "c-1", sender: "teacher", text: "That's wonderful, Sarah! How's the 4-7-8 pattern feeling?", timestamp: "Apr 8, 10:02 AM", read: true },
    { id: "m-1-4", conversationId: "c-1", sender: "member", text: "Really good! I've been doing it before bed and falling asleep so much faster.", timestamp: "Apr 8, 10:15 AM", read: true },
    { id: "m-1-5", conversationId: "c-1", sender: "teacher", text: "Looking forward to our session on Friday!", timestamp: "Apr 9, 10:32 AM", read: false },
  ],
  "c-2": [
    { id: "m-2-1", conversationId: "c-2", sender: "system", text: "Session completed: Yoga on Apr 3", timestamp: "Apr 3, 3:05 PM", read: true },
    { id: "m-2-2", conversationId: "c-2", sender: "teacher", text: "Great session today! Your warrior II is looking solid.", timestamp: "Apr 3, 3:30 PM", read: true },
    { id: "m-2-3", conversationId: "c-2", sender: "member", text: "Thanks Carlos! My hips are still pretty tight though.", timestamp: "Apr 3, 4:00 PM", read: true },
    { id: "m-2-4", conversationId: "c-2", sender: "teacher", text: "Great progress this week. Remember to practice the hip openers.", timestamp: "Apr 4, 9:00 AM", read: true },
  ],
  "c-3": [
    { id: "m-3-1", conversationId: "c-3", sender: "system", text: "Session scheduled: Meditation on Apr 18 at 9:00 AM", timestamp: "Apr 5, 11:00 AM", read: true },
    { id: "m-3-2", conversationId: "c-3", sender: "member", text: "Hi Lena, excited for our next session!", timestamp: "Apr 5, 11:30 AM", read: true },
    { id: "m-3-3", conversationId: "c-3", sender: "teacher", text: "Me too! Would you like to try a body scan meditation next time?", timestamp: "Apr 5, 2:00 PM", read: true },
    { id: "m-3-4", conversationId: "c-3", sender: "member", text: "Yes, that sounds perfect!", timestamp: "Apr 5, 2:30 PM", read: true },
    { id: "m-3-5", conversationId: "c-3", sender: "teacher", text: "I've sent you some guided meditation tracks to try before our next session.", timestamp: "Apr 6, 10:00 AM", read: false },
  ],
  "c-4": [
    { id: "m-4-1", conversationId: "c-4", sender: "system", text: "Session completed: Yoga on Mar 20", timestamp: "Mar 20, 4:05 PM", read: true },
    { id: "m-4-2", conversationId: "c-4", sender: "member", text: "James, that was an amazing session! Left a 5-star review.", timestamp: "Mar 20, 5:00 PM", read: true },
    { id: "m-4-3", conversationId: "c-4", sender: "teacher", text: "Thanks for the review! Really appreciate it.", timestamp: "Mar 21, 8:00 AM", read: true },
  ],
  "c-5": [
    { id: "m-5-1", conversationId: "c-5", sender: "system", text: "Session completed: Somatic on Mar 28", timestamp: "Mar 28, 12:05 PM", read: true },
    { id: "m-5-2", conversationId: "c-5", sender: "teacher", text: "How are you feeling after the somatic session?", timestamp: "Mar 29, 9:00 AM", read: false },
  ],
};

// ── Journey Data ──
export const disciplineBreakdown: DisciplineBreakdown[] = [
  { discipline: "Breathwork", sessions: 6, hours: 6 },
  { discipline: "Yoga", sessions: 5, hours: 5 },
  { discipline: "Meditation", sessions: 4, hours: 3.5 },
  { discipline: "Somatic", sessions: 1, hours: 1 },
  { discipline: "Somatic", sessions: 1, hours: 1 },
];

export const milestones: Milestone[] = [
  { id: "mi-1", title: "First Session", description: "Completed your first session", icon: "Sparkles", earned: true, earnedDate: "2025-10-10" },
  { id: "mi-2", title: "5 Sessions", description: "Completed 5 sessions", icon: "Trophy", earned: true, earnedDate: "2025-12-15" },
  { id: "mi-3", title: "3 Disciplines", description: "Tried 3 different disciplines", icon: "Palette", earned: true, earnedDate: "2026-01-20" },
  { id: "mi-4", title: "10 Hours", description: "10 hours of total practice", icon: "Clock", earned: true, earnedDate: "2026-02-28" },
  { id: "mi-5", title: "4 Week Streak", description: "4 weeks in a row", icon: "Flame", earned: true, earnedDate: "2026-03-28" },
  { id: "mi-6", title: "25 Sessions", description: "Complete 25 sessions", icon: "Award", earned: false },
  { id: "mi-7", title: "All Disciplines", description: "Try all 5 disciplines", icon: "Star", earned: false },
  { id: "mi-8", title: "50 Hours", description: "50 hours of total practice", icon: "Zap", earned: false },
];

export const journalEntries: JournalEntry[] = [
  { id: "j-1", date: "2026-04-07", teacherName: "Maya Reyes", discipline: "Breathwork", note: "Focused on box breathing and the 4-7-8 pattern. Felt deeply relaxed by the end. Maya suggested I try this before stressful meetings." },
  { id: "j-2", date: "2026-04-03", teacherName: "Carlos Vega", discipline: "Yoga", note: "Worked on hip openers and warrior series. My flexibility is definitely improving. Need to practice pigeon pose at home." },
  { id: "j-3", date: "2026-03-28", teacherName: "Anika Sharma", discipline: "Somatic", note: "First somatic session — very different from yoga. Focused on body awareness and releasing tension in my shoulders. Interesting experience." },
  { id: "j-4", date: "2026-03-24", teacherName: "Maya Reyes", discipline: "Meditation", note: "Tried guided visualization today. Found it harder to focus than breathwork but Maya was patient and helpful." },
  { id: "j-5", date: "2026-03-20", teacherName: "James Okafor", discipline: "Yoga", note: "Power flow session. James pushes me in a good way. My core is getting stronger." },
];

export const activityCalendar: ActivityDay[] = [
  { date: "2026-04-07", sessions: 1 },
  { date: "2026-04-03", sessions: 1 },
  { date: "2026-03-28", sessions: 1 },
  { date: "2026-03-24", sessions: 1 },
  { date: "2026-03-20", sessions: 1 },
  { date: "2026-03-17", sessions: 1 },
  { date: "2026-03-12", sessions: 1 },
  { date: "2026-03-07", sessions: 1 },
  { date: "2026-03-03", sessions: 1 },
  { date: "2026-02-27", sessions: 1 },
  { date: "2026-02-21", sessions: 1 },
  { date: "2026-02-14", sessions: 1 },
];

// ── Activity Feed ──
export const activityFeed: ActivityItem[] = [
  { id: "af-1", type: "session", message: "Session with Maya Reyes — Breathwork — Apr 7", date: "2026-04-07" },
  { id: "af-2", type: "review", message: "You left a 5-star review for Maya Reyes", date: "2026-04-07" },
  { id: "af-3", type: "session", message: "Session with Carlos Vega — Yoga — Apr 3", date: "2026-04-03" },
  { id: "af-4", type: "booking", message: "Booked session with Lena Park for Apr 18", date: "2026-04-01" },
  { id: "af-5", type: "session", message: "Session with Anika Sharma — Somatic — Mar 28", date: "2026-03-28" },
];

// ── Payment ──
export const paymentMethods: PaymentMethod[] = [
  { id: "pm-1", type: "visa", last4: "4242", expiry: "09/27", isDefault: true },
  { id: "pm-2", type: "mastercard", last4: "8888", expiry: "03/28", isDefault: false },
];

export const billingHistory: BillingRecord[] = [
  { id: "b-1", date: "2026-04-07", teacherName: "Maya Reyes", discipline: "Breathwork", amount: 65, status: "paid" },
  { id: "b-2", date: "2026-04-03", teacherName: "Carlos Vega", discipline: "Yoga", amount: 70, status: "paid" },
  { id: "b-3", date: "2026-03-28", teacherName: "Anika Sharma", discipline: "Somatic", amount: 85, status: "paid" },
  { id: "b-4", date: "2026-03-24", teacherName: "Maya Reyes", discipline: "Meditation", amount: 65, status: "paid" },
  { id: "b-5", date: "2026-03-20", teacherName: "James Okafor", discipline: "Yoga", amount: 75, status: "paid" },
  { id: "b-6", date: "2026-03-17", teacherName: "Lena Park", discipline: "Meditation", amount: 80, status: "paid" },
  { id: "b-7", date: "2026-03-15", teacherName: "David Cohen", discipline: "Meditation", amount: 85, status: "refunded" },
  { id: "b-8", date: "2026-03-12", teacherName: "Carlos Vega", discipline: "Yoga", amount: 70, status: "paid" },
  { id: "b-9", date: "2026-03-07", teacherName: "Maya Reyes", discipline: "Breathwork", amount: 65, status: "paid" },
  { id: "b-10", date: "2026-03-03", teacherName: "Kwame Mensah", discipline: "Meditation", amount: 70, status: "paid" },
];

export const notificationPrefs: NotificationPrefs = {
  emailReminders: true,
  smsReminders: false,
  marketingEmails: true,
};
