import { Review } from "./types";

export const reviews: Review[] = [
  // ── Published (11) ──
  { id: "r-1", memberName: "Jordan Lee", memberInitials: "JL", teacherName: "David Cohen", teacherInitials: "DC", discipline: "Meditation", rating: 5, comment: "David has an incredibly calming presence. The guided meditation was exactly what I needed to center myself after a stressful week. Highly recommend.", date: "2026-04-08", status: "published", helpful: 12 },
  { id: "r-2", memberName: "Sarah Chen", memberInitials: "SC", teacherName: "Carlos Vega", teacherInitials: "CV", discipline: "Yoga", rating: 5, comment: "Carlos is an amazing yoga instructor. His flow sequences are creative and challenging. I always leave feeling energized and refreshed.", date: "2026-04-07", status: "published", helpful: 8 },
  { id: "r-3", memberName: "Nina Patel", memberInitials: "NP", teacherName: "Maya Reyes", teacherInitials: "MR", discipline: "Breathwork", rating: 4, comment: "Great session! Maya introduced me to techniques I had never tried before. The only reason for 4 stars is the session felt a bit rushed towards the end.", date: "2026-04-07", status: "published", helpful: 6 },
  { id: "r-4", memberName: "Alex Kim", memberInitials: "AK", teacherName: "Anika Sharma", teacherInitials: "AS", discipline: "Somatic", rating: 5, comment: "Anika's somatic therapy is transformative. She helped me release tension I didn't even know I was holding. I've already booked my next session.", date: "2026-04-06", status: "published", helpful: 15 },
  { id: "r-5", memberName: "Amara Osei", memberInitials: "AO", teacherName: "Carlos Vega", teacherInitials: "CV", discipline: "Yoga", rating: 4, comment: "Solid yoga session with great adjustments and clear cues. Carlos really pays attention to each student's alignment and form.", date: "2026-04-05", status: "published", helpful: 4 },
  { id: "r-6", memberName: "Chloe Martin", memberInitials: "CM", teacherName: "James Okafor", teacherInitials: "JO", discipline: "Breathwork", rating: 3, comment: "The breathwork techniques were good, but I felt like the session was a bit too structured for my taste. Would have appreciated more flexibility to explore.", date: "2026-04-04", status: "published", helpful: 2 },
  { id: "r-7", memberName: "Marcus Johnson", memberInitials: "MJ", teacherName: "Lena Park", teacherInitials: "LP", discipline: "Meditation", rating: 5, comment: "Lena is a gifted teacher. Her voice is so soothing and her guidance through the meditation was perfect. Best meditation experience I've ever had.", date: "2026-04-03", status: "published", helpful: 18 },
  { id: "r-8", memberName: "Ethan Brooks", memberInitials: "EB", teacherName: "David Cohen", teacherInitials: "DC", discipline: "Somatic", rating: 4, comment: "David offered thoughtful insights and created a safe space for exploration. I left with a lot to reflect on. Very grateful for the session.", date: "2026-04-02", status: "published", helpful: 7 },
  { id: "r-9", memberName: "Sofia Rodriguez", memberInitials: "SR", teacherName: "Anika Sharma", teacherInitials: "AS", discipline: "Somatic", rating: 5, comment: "Absolutely incredible. Anika helped me connect with my body in a way I never thought possible. The progress I've made in just a few sessions is remarkable.", date: "2026-03-31", status: "published", helpful: 21 },
  { id: "r-10", memberName: "Kai Nakamura", memberInitials: "KN", teacherName: "Maya Reyes", teacherInitials: "MR", discipline: "Breathwork", rating: 4, comment: "Maya's breathwork sessions are always rejuvenating. She has a great balance of instruction and allowing space for personal practice.", date: "2026-03-28", status: "published", helpful: 5 },
  { id: "r-11", memberName: "David Park", memberInitials: "DP", teacherName: "Carlos Vega", teacherInitials: "CV", discipline: "Yoga", rating: 5, comment: "First time trying yoga and Carlos made it so welcoming. He was patient with my beginner level and offered great modifications. Will definitely continue.", date: "2026-03-25", status: "published", helpful: 9 },

  // ── Flagged (3) ──
  { id: "r-12", memberName: "Ryan Hughes", memberInitials: "RH", teacherName: "Carlos Vega", teacherInitials: "CV", discipline: "Yoga", rating: 1, comment: "Terrible experience. The teacher was rude and dismissive. Worst money I've ever spent. Don't waste your time with this joke of a platform.", date: "2026-04-01", status: "flagged", flagReason: "Inappropriate language and suspected retaliatory review after account ban", helpful: 0 },
  { id: "r-13", memberName: "Lucas Meyer", memberInitials: "LM", teacherName: "James Okafor", teacherInitials: "JO", discipline: "Breathwork", rating: 1, comment: "This teacher clearly has no qualifications. I could get better guidance from a YouTube video. Complete scam.", date: "2026-03-29", status: "flagged", flagReason: "Suspected fake review - member had a cancelled session, no completed session with this teacher", helpful: 1 },
  { id: "r-14", memberName: "Liam O'Brien", memberInitials: "LO", teacherName: "Lena Park", teacherInitials: "LP", discipline: "Meditation", rating: 2, comment: "Not worth the price. The meditation was basic and I could have done it myself. Very disappointed with the whole experience here.", date: "2026-03-20", status: "flagged", flagReason: "Review posted after account went inactive - possible bad faith", helpful: 0 },

  // ── Hidden (1) ──
  { id: "r-15", memberName: "Ryan Hughes", memberInitials: "RH", teacherName: "Anika Sharma", teacherInitials: "AS", discipline: "Somatic", rating: 1, comment: "This platform and its teachers are all frauds. Save your money.", date: "2026-03-15", status: "hidden", flagReason: "Spam / abusive content from banned member", helpful: 0 },

  // ── Disputed (2) ──
  { id: "r-16", memberName: "Tomas Rivera", memberInitials: "TR", teacherName: "Anika Sharma", teacherInitials: "AS", discipline: "Somatic", rating: 2, comment: "The session was uncomfortable and I felt pushed beyond my limits. The teacher didn't listen when I said I wanted to stop a particular exercise.", date: "2026-04-05", status: "disputed", disputeReason: "I always prioritize client comfort and asked Tomas multiple times if he wanted to continue. He said yes each time. I believe this review misrepresents what happened in the session.", helpful: 3 },
  { id: "r-17", memberName: "Emma Wilson", memberInitials: "EW", teacherName: "James Okafor", teacherInitials: "JO", discipline: "Breathwork", rating: 2, comment: "James was 10 minutes late and then cut the session short. I paid for a full hour and only got about 45 minutes of actual instruction.", date: "2026-03-22", status: "disputed", disputeReason: "I was on time for the session. There was a technical issue with the platform that delayed the start by a few minutes, which was beyond my control. I offered to extend the session but the member declined.", helpful: 1 },
];
